### ISSUE TITLE
Asian Studies should require a sequence of language courses

### ISSUE THREAD

**Issue by hawkrives** [hawkrives/gobbldygook-area-data#107]
The Asian Studies page says:

> Two courses in Chinese or Japanese above 112 or its equivalent.

Currently, the codified file says

``` yaml
Langauge:
    two of (
        CHIN 231, 232, 294, 298, 301, 302, 320, 351, 394, 398,
        JAPAN 231, 232, 294, 298, 301, 302, 320, 394, 398 )
```

However, that would allow a student to qualify with `CHIN 231` and `JAPAN 231`, which is not ideal.

It should be, instead,

``` yaml
Langauge:
    Chinese: two of ( CHIN 231, 232, 294, 298, 301, 302, 320, 351, 394, 398 )
    Japanese: two of ( JAPAN 231, 232, 294, 298, 301, 302, 320, 394, 398 )

    result: Chinese | Japanese
```

That is, it should require that the student take two courses within either language.

---

Devil's advocate: Or should it?

_Semantically_, I don't think the Asian Studies major would care if you passed with CHIN 231 and JAPAN 231, with the implied six courses of study it would take for that. 

Should the major file be flexible or strict?

(The correct answer is probably "ask the department"…)
