### ISSUE TITLE
Separate B.A. majors from B.M. majors?

### ISSUE THREAD

**Issue by hawkrives** [hawkrives/gobbldygook-area-data#113]
Given that B.A. majors are only available to B.A.s, and vice versa for B.M.s, I think we should figure out some way to pair them appropriately in the directory structure.

Maybe a new major type, `major-ba` vs. `major-bm`?

Gobbldygook proper shouldn't care; it'll need to be documented, though, as the new `given: areas of study` rule will rely on searching via type.

**Comment by hawkrives** [comment]
Alternate idea: Include a `degree` field that can be string-matched against the degree files' `name` fields.

```yaml
name: Mathematics
catalog: 2015-16
degree: Bachelor of Arts
type: Major
```
