### ISSUE TITLE
B.A. Music

### ISSUE THREAD

**Issue by hawkrives** [hawkrives/gobbldygook-area-data#126]
- [ ] can your "other lessons" happen simultaneously with your primary instrument's lessons?

So Music requires that you take six terms of lessons, total; four in a single instrument, and two from some other instrument.

I wound up breaking the requirement down a sub-requirement for each available type of instrument, and then breaking each of those into two children (Lessons and Other Lessons).

Lessons, then, says "this course must be taken for four terms", and Other Lessons says "courses that aren't $this_course must be taken for at least two terms".

That would ordinarily allow for overlap between the two requirements, where Other Lessons could happen at the same time as the Lessons; in order to avoid that, I applied a `count >= 6` to the parent requirement for each pair.

```yaml
Bassoon:
  result:
    given: these requirements
    requirements: [{requirement: Lessons}, {requirement: Other Lessons}]
    what: terms
    do: count >= 6
  requirements:
    Lessons:
      result: 
        given: these courses
        courses: [MUSPF 102]
        repeats: all
        what: terms
        do: count >= 4
    Other Lessons:
      result: 
        given: courses
        where: {department: MUSPF, number: '! 102'}
        what: terms
        do: count >= 2
```

If it turns out that they can overlap, we can change them to the following:

```yaml
Bassoon:
  result:
    both: [{requirement: Lessons}, {requirement: Other Lessons}]
  requirements:
    Lessons:
      result: 
        given: these courses
        courses: [MUSPF 102]
        repeats: all
        what: terms
        do: count >= 4
    Other Lessons:
      result: 
        given: courses
        where: {department: MUSPF, number: '! 102'}
        what: terms
        do: count >= 2
```

---

I'm still thinking about how to make a specific shorthand for this type of requirement; if I find another major that needs this, I'll make it a higher priority.

**Comment by hawkrives** [comment]
music performances record if they were passed by testing out?

represent as overrides?

**Comment by hawkrives** [comment]
MUSIC 161 + MUSIC 162 both require at least a B-

**Comment by hawkrives** [comment]
SIS has "Orgs and Awards"

---

I think this part:

> Two solo performances on a St. Olaf Student Recital.

can be replaced with 

```yaml
given: music performances
where: {performance: 'Instrumental Student Recital | Vocal Lab Choir Solo'}
what: performances
do: count >= 2
```

---

now, this part…

> Ten recitals per semester on campus, with a minimum of 60.

```yaml
saves:
- given: music performance attendances
  what: performances
  do: count >= 60
```

except that doesn't handle "per semester on campus"…
